service: trade
runtime: python312

default_expiration: "1h"

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
  mime_type: image/x-icon
  expiration: "7d"
  secure: always

- url: /styles.css
  static_files: styles.css
  upload: styles.css
  mime_type: text/css
  expiration: "1h"
  secure: always

- url: /(.+\.js)
  static_files: \1
  upload: (.+\.js)
  mime_type: application/javascript
  expiration: "1h"
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  mime_type: text/html
  expiration: "5m"
  secure: always

- url: /(.*)
  static_files: \1
  upload: (.*)
  secure: always
