const QAReportEngine = (() => {

    const qaReportData = [
        {
            phase: "Phase 1 — Logic Audit",
            bugs: [
                {
                    id: "LOGIC-001",
                    severity: "Moderate",
                    location: "market-data.js : _updateCandles",
                    description: "Candle timestamps drift if local clock is out of sync with market open time, causing duplicate candle creation on high timeframes.",
                    reproduction: "Run the app at 9:30 AM EST market open. The 1h modulo calculation expects 9:00 AM, causing the 9:30 AM server candle to prematurely close.",
                    fix: "Anchor all modulo timeframe bounding strictly to 9:30 AM EST start-of-day offset rather than standard UNIX 0 timestamp."
                },
                {
                    id: "LOGIC-002",
                    severity: "Minor",
                    location: "agent-framework.js : runCycle",
                    description: "Risk alerts generated by the framework do not always clear immediately when transitioning from a high-volatility tick to a low-volatility tick.",
                    reproduction: "Spike VIX manually via data injection, wait 1 cycle, drop VIX to 0. The anomaly badge remains 'ALERT' for an extra cycle.",
                    fix: "Ensure state mutations for derived values flush synchronously at the end of the tick cycle rather than relying on the next loop."
                }
            ]
        },
        {
            phase: "Phase 2 — Component Audit",
            bugs: [
                {
                    id: "COMP-001",
                    severity: "Minor",
                    location: "dashboard.js : updateAgentTable",
                    description: "Agent table crashes if 'optionsStrategies' array is undefined when rendering the recommendations panel.",
                    reproduction: "Mock a backend response where options data is completely omitted. The UI throws a TypeError.",
                    fix: "Add default fallback `[]` or optional chaining `rec.optionsStrategies?.length` before mapping the UI elements."
                },
                {
                    id: "COMP-002",
                    severity: "Critical",
                    location: "chart-engine.js : setData",
                    description: "Lightweight Charts throws a fatal unhandled exception if candle data array contains items with identical UNIX timestamps.",
                    reproduction: "Fast-click the 1M to 5M timeframe buttons while data is actively streaming via WebSocket.",
                    fix: "Implement a deep deduplication step `filter((v,i,a) => a.findIndex(t=>t.time===v.time)===i)` before calling `setData`."
                }
            ]
        },
        {
            phase: "Phase 3 — User Flow Audit",
            bugs: [
                {
                    id: "FLOW-001",
                    severity: "Moderate",
                    location: "backtest-engine.js : runBacktest",
                    description: "Secondary state (selected algorithm buttons, date picker UI) is not fully reset when closing and reopening the Backtest Engine Modal.",
                    reproduction: "Open Backtest -> Select 'Transformer' and '5 Days' -> Close Modal -> Reopen. The UI says 'Transformer' but internal state defaults back to 'Ensemble'.",
                    fix: "Hook `resetBacktestState()` into the modal's close button event listener to wipe secondary state elements."
                }
            ]
        },
        {
            phase: "Phase 4 — Edge Case Audit",
            bugs: [
                {
                    id: "EDGE-001",
                    severity: "Moderate",
                    location: "dashboard.js : wireHeaderActions",
                    description: "Clicking 'Clear Cache' wipes localStorage completely, which previously deleted API keys and broke the app until legacy checks were removed.",
                    reproduction: "Click 🧹. Application reloads. Any settings saved in `sessionStorage` or preferences are permanently vaporized without backup.",
                    fix: "Implement selective cache clearing (only wipe `caches` and Service Worker) and preserve user configuration keys in `localStorage`."
                },
                {
                    id: "EDGE-002",
                    severity: "Minor",
                    location: "live-market-connector.js : setTicker",
                    description: "Changing tickers extremely rapidly leaves phantom data from the previous ticker visible in the FinMem quote box.",
                    reproduction: "Spam click different assets in the Watchlist sidebar. The chart updates, but the FinMem panel occasionally lags and displays the old stock's summary.",
                    fix: "Implement an AbortController or generation ID on the AI summary fetch to drop stale promises when the user switches context."
                }
            ]
        }
    ];

    function init() {
        const topBarRight = document.querySelector('.top-bar-right');
        if (!topBarRight) return;

        // Add Cogwheel Admin Button
        const adminBtn = document.createElement('button');
        adminBtn.innerHTML = '⚙️';
        adminBtn.title = "QA Admin Panel";
        adminBtn.className = "header-btn";
        adminBtn.style.cssText = "background:transparent; border:none; cursor:pointer; font-size:14px; padding:0 4px; transition:color 0.2s; filter: grayscale(1); opacity: 0.5;";
        
        adminBtn.onmouseover = () => { adminBtn.style.opacity = '1'; adminBtn.style.filter = 'none'; };
        adminBtn.onmouseout = () => { adminBtn.style.opacity = '0.5'; adminBtn.style.filter = 'grayscale(1)'; };

        // Insert before clear cache button
        const clearCacheBtn = document.getElementById('clear-cache-btn');
        if (clearCacheBtn) {
            topBarRight.insertBefore(adminBtn, clearCacheBtn);
            const sep = document.createElement('span');
            sep.className = 'sep';
            sep.textContent = '|';
            topBarRight.insertBefore(sep, clearCacheBtn);
        } else {
            topBarRight.appendChild(adminBtn);
        }

        // Build Modal
        const modalHtml = `
            <div id="qa-admin-modal" class="bt-modal-overlay" style="display:none; z-index: 99999;">
                <div class="bt-modal" style="max-width: 800px; max-height: 85vh; overflow-y: auto;">
                    <div class="bt-modal-header" style="border-bottom: 1px solid #334155; padding-bottom: 15px; margin-bottom: 20px;">
                        <div class="bt-modal-title" style="color: #a78bfa;">
                            <span class="bt-icon">⚙️</span> SYSTEM QA AUDIT REPORT
                        </div>
                        <button class="bt-close" id="qa-close-btn">✕</button>
                    </div>
                    <div id="qa-report-content" style="font-size: 12px; color: #cbd5e1; line-height: 1.5;">
                        <!-- Content Injected Here -->
                    </div>
                </div>
            </div>
        `;
        document.body.insertAdjacentHTML('beforeend', modalHtml);

        const modal = document.getElementById('qa-admin-modal');
        const closeBtn = document.getElementById('qa-close-btn');

        adminBtn.addEventListener('click', () => {
            renderReport();
            modal.style.display = 'flex';
        });

        closeBtn.addEventListener('click', () => {
            modal.style.display = 'none';
        });

        modal.addEventListener('click', (e) => {
            if (e.target === modal) modal.style.display = 'none';
        });
    }

    function renderReport() {
        const container = document.getElementById('qa-report-content');
        let html = '';

        qaReportData.forEach(phase => {
            html += `<h2 style="color: #e2e8f0; border-bottom: 1px solid #1e293b; padding-bottom: 5px; margin-top: 20px; font-size: 14px;">${phase.phase}</h2>`;
            
            phase.bugs.forEach(bug => {
                let badgeColor = bug.severity === 'Critical' ? '#ef4444' : bug.severity === 'Moderate' ? '#f97316' : '#eab308';
                
                html += `
                <div style="background: rgba(15, 23, 42, 0.6); border: 1px solid #334155; border-radius: 6px; padding: 12px; margin-top: 10px;">
                    <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;">
                        <span style="font-family: 'JetBrains Mono', monospace; color: #38bdf8; font-weight: bold;">[${bug.id}]</span>
                        <span style="background: ${badgeColor}; color: #000; padding: 2px 6px; border-radius: 4px; font-size: 10px; font-weight: bold;">${bug.severity.toUpperCase()}</span>
                    </div>
                    <div style="margin-bottom: 6px;">
                        <span style="color: #94a3b8; font-size: 11px;">📍 Location:</span> 
                        <span style="font-family: 'JetBrains Mono', monospace; font-size: 11px;">${bug.location}</span>
                    </div>
                    <div style="margin-bottom: 6px;">
                        <span style="color: #94a3b8; font-size: 11px;">🐛 Bug:</span> 
                        <span>${bug.description}</span>
                    </div>
                    <div style="margin-bottom: 6px;">
                        <span style="color: #94a3b8; font-size: 11px;">🔄 Repro:</span> 
                        <span style="color: #a78bfa; font-style: italic;">${bug.reproduction}</span>
                    </div>
                    <div style="margin-top: 8px; padding-top: 8px; border-top: 1px dashed #334155;">
                        <span style="color: #94a3b8; font-size: 11px;">🛠️ Recommended Fix:</span> 
                        <span style="color: #22c55e;">${bug.fix}</span>
                    </div>
                </div>
                `;
            });
        });

        container.innerHTML = html;
    }

    // Auto-init on load
    document.addEventListener('DOMContentLoaded', init);

    return { init, renderReport };
})();
